//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.invoiceheaders = new HashSet<invoiceheader>();
            this.projects = new HashSet<project>();
        }
    
        public System.Guid id { get; set; }
        public string clientname { get; set; }
        public string address { get; set; }
        public string abn { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public double taxrate { get; set; }
        public bool isme { get; set; }
        public int currentInvoiceNumber { get; set; }
    
        public virtual ICollection<invoiceheader> invoiceheaders { get; set; }
        public virtual ICollection<project> projects { get; set; }
    }
}
