//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceheader
    {
        public invoiceheader()
        {
            this.invoicelines = new HashSet<invoiceline>();
        }
    
        public System.Guid id { get; set; }
        public int number { get; set; }
        public System.DateTime datecreated { get; set; }
        public Nullable<double> hourlyrate { get; set; }
        public Nullable<double> taxrate { get; set; }
        public System.Guid fk_client { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<invoiceline> invoicelines { get; set; }
    }
}
