//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceline
    {
        public System.Guid id { get; set; }
        public int number { get; set; }
        public System.DateTime datecompleted { get; set; }
        public string description { get; set; }
        public Nullable<double> hourlyrate { get; set; }
        public double hours { get; set; }
        public Nullable<System.Guid> fk_project { get; set; }
        public System.Guid fk_invoiceheader { get; set; }
    
        public virtual invoiceheader invoiceheader { get; set; }
        public virtual project project { get; set; }
    }
}
