//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.invoicelines = new HashSet<invoiceline>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public double hourlyrate { get; set; }
        public System.Guid fk_client { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<invoiceline> invoicelines { get; set; }
    }
}
